CREATE TABLE `User`
(
ID VARCHAR(32) NOT NULL PRIMARY KEY,
Name VARCHAR(20) NULL,
Creator VARCHAR(32) NULL,
CreateTime DATETIME NULL,
`Password` VARCHAR(50) NULL,
`Enabled` BIT NULL,
LastUpdateTime DATETIME NULL,
LastUpdator VARCHAR(32) NULL
);

CREATE TABLE UserInfo
(
ID VARCHAR(32) NOT NULL PRIMARY KEY,
QQ VARCHAR(20) NULL,
Mobile VARCHAR(20) NULL,
WX VARCHAR(30) NULL,
`Address` NVARCHAR(100) NULL,
`Identity` VARCHAR(20) NULL
);

CREATE TABLE Menu
(
ID VARCHAR(32) NOT NULL PRIMARY KEY,
Name VARCHAR(20) NULL,
Creator VARCHAR(32) NULL,
CreateTime DATETIME NULL,
`Page` VARCHAR(50) NULL,
ParentID VARCHAR(32) NULL,
`Enabled` BIT NULL,
Remark NVARCHAR(500) NULL,
LastUpdateTime DATETIME NULL,
LastUpdator VARCHAR(32) NULL
);

CREATE TABLE `Role`
(
ID VARCHAR(32) NOT NULL PRIMARY KEY,
Name VARCHAR(20) NULL,
Creator VARCHAR(32) NULL,
CreateTime DATETIME NULL,
Remark NVARCHAR(500) NULL,
LastUpdateTime DATETIME NULL,
LastUpdator VARCHAR(32) NULL
);

CREATE TABLE `Post`
(
ID VARCHAR(32) NOT NULL PRIMARY KEY,
Name VARCHAR(20) NULL,
Creator VARCHAR(32) NULL,
CreateTime DATETIME NULL,
Remark NVARCHAR(500) NULL,
LastUpdateTime DATETIME NULL,
LastUpdator VARCHAR(32) NULL
);

CREATE TABLE User_Role
(
ID VARCHAR(32) NOT NULL PRIMARY KEY,
UserID VARCHAR(32) NULL,
RoleID VARCHAR(32) NULL
);

CREATE TABLE User_Post
(
ID VARCHAR(32) NOT NULL PRIMARY KEY,
UserID VARCHAR(32) NULL,
PostID VARCHAR(32) NULL
);

CREATE TABLE Menu_Role
(
ID VARCHAR(32) NOT NULL PRIMARY KEY,
MenuID VARCHAR(32) NULL,
RoleID VARCHAR(32) NULL
);


CREATE TABLE Module
(
ID VARCHAR(32) NOT NULL PRIMARY KEY,
Name VARCHAR(20) NULL,
Creator VARCHAR(32) NULL,
CreateTime DATETIME NULL,
Remark NVARCHAR(500) NULL,
LastUpdateTime DATETIME NULL,
LastUpdator VARCHAR(32) NULL
);


CREATE TABLE `Action`
(
ID VARCHAR(32) NOT NULL PRIMARY KEY,
Name VARCHAR(20) NULL,
Creator VARCHAR(32) NULL,
CreateTime DATETIME NULL,
Remark NVARCHAR(500) NULL,
LastUpdateTime DATETIME NULL,
LastUpdator VARCHAR(32) NULL
);

CREATE TABLE Role_Module_Action
(
ID VARCHAR(32) NOT NULL PRIMARY KEY,
RoleID VARCHAR(32) NULL,
ModuleID VARCHAR(32) NULL,
ActionID VARCHAR(32) NULL
);

CREATE TABLE LogonHistory
(
ID VARCHAR(32) NOT NULL PRIMARY KEY,
UserID VARCHAR(32) NULL,
Token VARCHAR(32) NULL,
LogonTime DATETIME NULL,
IP VARCHAR(15) NULL,
ActiveTime DATETIME NULL
);