CREATE TABLE [User]
(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
Name VARCHAR(20) NULL,
Creator VARCHAR(26) NULL,
CreateTime DATETIME NULL,
[Password] VARCHAR(50) NULL,
[Enabled] BIT NULL
);

CREATE TABLE UserInfo
(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
QQ VARCHAR(20) NULL,
Mobile VARCHAR(20) NULL,
WX VARCHAR(30) NULL,
[Address] NVARCHAR(100) NULL
);

CREATE TABLE Menu
(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
Name VARCHAR(20) NULL,
Creator VARCHAR(26) NULL,
CreateTime DATETIME NULL,
[Page] VARCHAR(50) NULL,
ParentID VARCHAR(26) NULL,
[Enabled] BIT NULL,
Remark NVARCHAR(500) NULL
);

CREATE TABLE [Role]
(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
Name VARCHAR(20) NULL,
Creator VARCHAR(26) NULL,
CreateTime DATETIME NULL,
Remark NVARCHAR(500) NULL
);

CREATE TABLE [Post]
(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
Name VARCHAR(20) NULL,
Creator VARCHAR(26) NULL,
CreateTime DATETIME NULL,
Remark NVARCHAR(500) NULL
);

CREATE TABLE User_Role
(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
UserID VARCHAR(26) NULL,
RoleID VARCHAR(26) NULL
);

CREATE TABLE User_Post
(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
UserID VARCHAR(26) NULL,
PostID VARCHAR(26) NULL
);

CREATE TABLE Menu_Role
(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
MenuID VARCHAR(26) NULL,
RoleID VARCHAR(26) NULL
);