/**
 * 项目信息form表单：新贷款资料
 * @authors viktorli (i@lizhenwen.com)
 * @date    2015-07-21 21:00:52
 */

define(function(require, exports, module){
	var MOD = [
		[{
			type:'label',
			col:3,
			required:true,
			html:'新贷款银行'
		},{
			col:"3",
			type:'select',
			name:'NewCreditBank',
			required:true,
			options:'银行'
		},{
			type:'label',
			col:3,
			required:true,
			html:'新贷款银行支行'
		},{
			col:"3",
			type:'text',
			name:'NewCreditBranch',
			required:true
		}],

		[{
			type:'label',
			col:3,
			html:'担保金额'
		},{
			col:'3',
			type:'number',
			required:true,
			name:'GuaranteeMoney',
			placeholder:'',
			suffix:'万元'
		},{
			type:'label',
			col:'3',
			required:true,
			html:'担保期限'
		},{
			col:'3',
			type:'number',
			required:true,
			name:'GuaranteeMonth',
			placeholder:'',
			suffix:'月'
		}],

		[{
			type:'label',
			col:'3',
			required:true,
			html:'买方贷款金额'
		},{
			col:'3',
			type:'number',
			required:true,
			name:'BuyerCreditCommerceMoney',
			placeholder:'',
			prefix:'商业',
			suffix:'万元'
		},{
			col:'3',
			type:'number',
			name:'BuyerCreditFundMoney',
			placeholder:'',
			prefix:'公积金',
			suffix:'万元'
		}],

		[{
			type:'label',
			col:3,
			required:true,
			html:'成交金额'
		},{
			col:"3",
			type:'number',
			name:'DealMoney',
			required:true,
			suffix:'万元'
		},{
			type:'label',
			col:3,
			required:true,
			html:'交易定金'
		},{
			col:"3",
			type:'number',
			name:'EarnestMoney',
			required:true,
			suffix:'万元'
		}],

		[{
			type:'label',
			col:3,
			required:true,
			html:'资金监管'
		},{
			col:"3",
			type:'number',
			name:'SupervisionMoney',
			required:true,
			suffix:'万元'
		},{
			type:'label',
			col:3,
			required:true,
			html:'资金监管银行'
		},{
			col:"3",
			type:'select',
			name:'SupervisionBank',
			options:'银行',
			required:true
		}],

		[{
			type:'label',
			col:3,
			html:'客户预存款'
		},{
			col:"3",
			type:'number',
			name:'CustomerPredepositMoney',
			suffix:'万元'
		}],

		[{
			type:'label',
			col:3,
			required:true,
			html:'贷款接收账户'
		},{
			col:"3",
			type:'text',
			name:'CreditReceiverName',
			placeholder:'姓名',
			required:true
		},{
			col:"3",
			type:'select',
			name:'CreditReceiverBank',
			remark:'银行 - 支行',
			options:'银行',
			required:true
		},{
			col:"3",
			type:'text',
			name:'CreditReceiverAccount',
			placeholder:'账号',
			required:true
		}]
	];

	return MOD;
});